config/routes.rb
Rails.application.routes.draw do
  # resources :usercommentratings
  # devise_for :users
  # resources :posts_users_read_statuses
  post '/topics/:topic_id/posts/:post_id/posts_users_read_statuses',to: 'posts_users_read_statuses#create'
  post '/posts/:post_id/posts_users_read_statuses',to: 'posts_users_read_statuses#create'
  devise_for :users
  devise_scope :user do

    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments do
    resources :usercommentratings
  end
  resources :posts do
    resources :ratings

  end

  resources :tags

  resources :topics do
    resources :posts
  end
  resources :posts
  resources  :posts do
    resources :comments
  end
  # resources :topics
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post,foreign_key:'post_id',optional:true,counter_cache: true
  has_many :usercommentratings
  has_many :users, :through => :usercommentratings

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :get_comment
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
    authorize! :edit,@comment
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_comments_path(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_comments_path(@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    authorize! :destroy,@comment
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_comments_path(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def get_comment
    @post=Post.find(params[:post_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>
<!--  <p>-->
<!--    <strong>Rating:</strong>-->
    <%#= comment.rating %>
<!--  </p>-->

</div>

app/views/comments/_form.html.erb
<%= form_with(model:[@post,comment],local:true) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%#= form.label :post_id, style: "display: block" %>
    <%= form.text_field :post_id,type:'hidden' %>
  </div>
  <div>
    <%= form.text_field :user_id,value:current_user.id,type:"hidden" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", post_comment_path(@post,@comment) %> |
  <%= link_to "Back to comments", post_comments_path(@post) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    By: <%= comment.user.email if comment.user %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", post_comment_path(@post,comment) %>
    </p>
    <p>
      <%= link_to "Add User Ratings",comment_usercommentratings_path(comment) %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_post_comment_path(@post) %>
<%= link_to "Back to posts", @post %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", post_comments_path(@post) %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_post_comment_path(@post,@comment) %> |
  <%= link_to "Back to comments", post_comments_path(@post) %>

  <%= button_to "Destroy this comment", post_comment_path(@post,@comment), method: :delete %>
</div>