config/routes.rb
Rails.application.routes.draw do
  # resources :usercommentratings
  # devise_for :users
  # resources :posts_users_read_statuses
  post '/topics/:topic_id/posts/:post_id/posts_users_read_statuses',to: 'posts_users_read_statuses#create'
  post '/posts/:post_id/posts_users_read_statuses',to: 'posts_users_read_statuses#create'
  devise_for :users
  devise_scope :user do

    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments do
    resources :usercommentratings
  end
  resources :posts do
    resources :ratings

  end

  resources :tags

  resources :topics do
    resources :posts
  end
  resources :posts
  resources  :posts do
    resources :comments
  end
  # resources :topics
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts ,dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:field)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-4">
    <%= form.label :field, style: "display: block",class:"form-label" %>
    <%= form.text_field :field,class:"form-control" %>
  </div>

  <div class="actions ">
    <%= form.submit "Update",class:"btn btn-primary"%>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">

  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Topic</h5>
      <p>
        <strong>Field:</strong>
        <%= topic.field %>
      </p>
    </div>
  </div>


</div>

app/views/topics/edit.html.erb
<h1 class="text-center mt-4">Edit topic</h1>



<br>
<div class="container col-5 mt-4">
  <%= render "form", topic: @topic %>
  <br />
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->
<h1 class="text-center mt-4">Topics</h1>
<div class="container col-4">
  <table class="table ">
    <thead>
    <tr>
      <th scope="col" colspan="1"></th>
      <th scope="col" colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <div id="topics">
      <% @topics.each do |topic| %>
        <tr>

          <td ><%= topic.field %></td>
          <td><%= button_to "Show this topic",topic,method: "get",class:"btn btn-primary" %></td>
      <% end %>

      </tr>
    </div>

    </tbody>
  </table>
  <%= button_to "New topic", new_topic_path,method: "get",class:"btn btn-primary" %>

</div>

<%#= link_to "Posts",posts_path %>

app/views/topics/new.html.erb
<h1 class="text-center mt-4">New topic</h1>



<br>

<div class="container col-5 mt-4">
  <%= render "form", topic: @topic %>
  <br />
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @topic %>
<br />
<div class="container col-4 mt-4">
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h5 class="card-title">Topic</h5>
      <p>
        <strong>Field:</strong>
        <%= @topic.field %>
      </p>
      <div class="row">
        <div class="col"><%= button_to "Edit", edit_topic_path(@topic),class:"btn btn-primary",method: "get" %></div>
        <div class="col"><%= button_to "Back", topics_path,class:"btn btn-primary",method: "get" %></div>
        <div class="col"><%= button_to "Posts", topic_posts_path(@topic),class:"btn btn-primary",method: "get" %></div>


      </div>
    </br>
      <%= button_to "Destroy this topic", @topic, method: :delete,class:"btn btn-danger",method: "delete" %>
    </div>
  </div>


</div>

<!--<div>-->
<!--  <%#= link_to "Edit this topic", edit_topic_path(@topic) %> |-->
  <%#= link_to "Back to topics", topics_path %>
  <%#= link_to "Add post", topic_posts_path(@topic) %>

  <%#= button_to "Destroy this topic", @topic, method: :delete %>
<!--</div>-->