config/routes.rb
Rails.application.routes.draw do
  # resources :usercommentratings
  # devise_for :users
  # resources :posts_users_read_statuses
  post '/topics/:topic_id/posts/:post_id/posts_users_read_statuses',to: 'posts_users_read_statuses#create'
  post '/posts/:post_id/posts_users_read_statuses',to: 'posts_users_read_statuses#create'
  devise_for :users
  devise_scope :user do

    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments do
    resources :usercommentratings
  end
  resources :posts do
    resources :ratings

  end

  resources :tags

  resources :topics do
    resources :posts
  end
  resources :posts
  resources  :posts do
    resources :comments
  end
  # resources :topics
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { maximum: 20,too_long: "%{count} characters is the maximum allowed"  }
  belongs_to :user
  belongs_to :topic,optional:true,foreign_key:'topic_id'
  has_many :comments,dependent: :destroy
  has_many :taggables,dependent: :destroy
  has_many :tags,through: :taggables
  has_many :ratings
  has_one_attached :cover_picture
  has_many :posts_users_read_statuses
  has_many :users, :through => :posts_users_read_statuses
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :get_post
  before_action :set_post, only: %i[ show edit update destroy ]
  # before_action :get_read
  # before_action :get_user
  # GET /posts or /posts.json
  def index
    # @posts_users_read_status = PostsUsersReadStatus.new


    if params[:topic_id].present?
      @posts = @topic.posts.paginate(page: params[:page],per_page: 2)
    else
      # @posts = Post.all.paginate(page: params[:page],per_page: 2)
      @search =DatePicker.new(params[:search])
      @result = @search.scope
      @posts=@result.paginate(page: params[:page],per_page: 2)



    end
    if params[:topic_id].present?
      @post = @topic.posts.build
    else
      @post=Post.new
    end

    # @read=PostsUsersReadStatus.where(post_id: @post.id,user_id: current_user.id).last
  end

  # GET /posts/1 or /posts/1.json
  def show
    # @posts_users_read_status = PostsUsersReadStatus.new
    if params[:topic_id].present?
      @post=@topic.posts.find(params[:id])
    else
      @post=Post.find(params[:id])
    end
    @read=PostsUsersReadStatus.where(post_id: @post.id,user_id: current_user.id).last
  end

  # GET /posts/new
  def new
    if params[:topic_id].present?
      @post = @topic.posts.build
    else
      @post=Post.new
    end

  end

  # GET /posts/1/edit
  def edit
    authorize! :edit,@post
  end

  # POST /posts or /posts.json
  def create
    if params[:topic_id].present?

      @post = @topic.posts.build(post_params.except(:tags))
      create_or_delete_posts_tags(@post,params[:post][:tags])
      respond_to do |format|
        if @post.save
          # format.js { render 'posts/show_updated_view'}
          format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }

        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors.to_json, status: :unprocessable_entity }

        end
      end
    else
      @post=Post.new(post_params.except(:tags))
      create_or_delete_posts_tags(@post,params[:post][:tags])
      respond_to do |format|
        if @post.save
          format.html { redirect_to posts_path, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end

    end



  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if params[:topic_id].present?
      respond_to do |format|
        if @post.update(post_params.except(:tags))
          create_or_delete_posts_tags(@post,params[:post][:tags])
          format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
        end
    else

        respond_to do |format|
          if @post.update(post_params.except(:tags))
            create_or_delete_posts_tags(@post,params[:post][:tags])
            format.html { redirect_to post_path(@post), notice: "Post was successfully updated." }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end


    end


  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize! :destroy,@post
    @post.destroy
    if params[:topic_id].present?
      respond_to do |format|
        format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to posts_path(@post), notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end

    end

  end

  private

  def create_or_delete_posts_tags(post,tags)
    post.taggables.destroy_all
    tags=tags.strip.split(',')
    tags.each do |tag|
      post.tags << Tag.find_or_create_by(name: tag)
    end
  end
  def get_post
    if params[:topic_id].present?
      @topic=Topic.find(params[:topic_id])

    end

  end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      if params[:topic_id].present?
        @post = @topic.posts.find(params[:id])

      else
        @post=Post.find(params[:id])

      end

    end
  # def get_read
  #   @read=PostsUsersReadStatus.where(post_id: @post.id,user_id: current_user.id).last
  # end
  # def get_user
  #   @user=User.find(params[:@post.user_id])
  # end
    # Only allow a list of trusted parameters through.
    def post_params
      if params[:topic_id].present?
        params.require(:post).permit(:title, :body, :topic_id, :tags, :cover_picture, :user_id)
      else
        params.require(:post).permit(:title, :body, :tags, :cover_picture, :user_id)

      end

    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model:[@topic,post],local: false,:html => {:class => "form"}) do |form| %>
  <div class="modal-body">
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-4">
      <%= form.text_field :title,class:"form-control",placeholder:"Title" %>
    </div>

    <div class="form-group mb-4">

      <%= form.text_area :body,class:"form-control",placeholder:"Body" %>
    </div>
    <div class="form-group mb-4">

      <%= form.text_field :tags,value: post.tags.map(&:name).join(","),class:"form-control",placeholder:"Tags" %>
    </div>
    <br />
    <div class="form-group mb-4">
      <%= form.label :"Cover Picture", style: "display: block" %>

      <%= form.file_field :cover_picture ,class:"form-control"%>
    </div>

    <div class="form-group mb-4">
      <%= form.text_field :topic_id ,type:"hidden"%>
    </div>
    <div>
      <%= form.text_field :user_id,value:current_user.id,type:"hidden" %>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<%#= current_user.inspect %>

<% end %>

app/views/posts/_index.html.erb
<div class="seen">
  <%if @read %>
    <p>Read</p>
  <%else %>
    <p>Unread</p>
  <%end %>
</div>

app/views/posts/_post.html.erb
<div class="card" style="width: 18rem;">


  <div class="card-body">
    <% if params[:topic_id].present? %>
      <h5 class="card-title"><%= post.title %>(<%=post.topic.field %>)</h5>
    <%end %>

    <p class="card-text">
    <p>
      <strong>Title:</strong>
      <%= post.title %>
    </p>

<!--    <p>-->
<!--      <strong>Body:</strong>-->
      <%#= post.body %>
<!--    </p>-->

    <p>
      <strong>Created By:</strong>
      <%= post.user.email if post.user %>
    </p>

    <%= post.rating_avg %>
    <p>Comments (<%= post.comments.size if post.comments%>)</p>
    <% post.ratings.group(:star).count.each do |value,count| %>

      <% for i in (1..value) do %>
        <span class="fa fa-star" style="color:orange"></span>
      <%end %>
      <% for i in (1..(5-value)) do %>
        <span class="fa fa-star "></span>
      <%end %>
      <%= count %>
      <br />
    <% end %>
    </p>
    <% if params[:topic_id].present? %>
      <p>
        <%= link_to "Show this post", topic_post_path(@topic,post),class:"btn btn-primary" %>
      </p>
    <%else %>
      <p>
        <%= link_to "Show this post",post_path(post),remote: true%>
      </p>
     <%end %>
  </div>

app/views/posts/edit.html.erb
<h1 class="text-center mt-4">Edit post</h1>
<br/>

<div class="container col-5 mt-4">
  <%= render "form", post: @post %>
  <%= link_to "Show this post", params[:topic_id].present? ? [@topic,@post] :post_path(@post) %> |
  <%= link_to "Back to posts", params[:topic_id].present? ? topic_posts_path(@topic) : posts_path %>
</div>

app/views/posts/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->
<style>
    .loader {
        border: 5px solid #f3f3f3;
        -webkit-animation: spin 1s linear infinite;
        animation: spin 1s linear infinite;
        border-top: 5px solid #555;
        border-radius: 50%;
        width: 50px;
        height: 50px;
        position: relative;
        left:47%;
    }
    /*.loader {*/
    /*    border: 16px solid #f3f3f3; !* Light grey *!*/
    /*    border-top: 16px solid #3498db; !* Blue *!*/
    /*    border-radius: 50%;*/
    /*    width: 120px;*/
    /*    height: 120px;*/
    /*    animation: spin 2s linear infinite;*/
    /*}*/

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
    .hide{
        display: none;
    }
    .date{
        margin-left: 50px;
    }
    .date-in{
        margin-left: 500px;
        margin-top: 30px;
        margin-bottom: 30px;
    }
    .l{
        margin-left:400px;
        margin-top:40px;
    }
</style>
<h1 class="text-center mt-4">Posts</h1>
<div class="loader hide"></div>
  <div class="date">
    <div class="date-in">
      <%= form_tag posts_path, method: :get do %>
        <%= date_field_tag 'search[date_from]',Date.today-2 %>
        <%= date_field_tag 'search[date_to]',Date.today %>
        <%= submit_tag "Search" %>
      <% end %>

    </div>

  <div>
<div class="container col-6 mt-4">


    <div id="posts" class="row" >
        <% @posts.each do |post| %>
          <div class=" col">
            <%# if params[:topic_id].present? %>
              <%= render post %>

              <% @read=PostsUsersReadStatus.where(post_id: post.id,user_id: current_user.id).last%>
               <div class="seen">

               </div>

          </div>

          </div>

        <% end %>




    </div>
  </div>
</div>
<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">-->
<!--  Launch demo modal-->
<!--</button>-->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="newUserForm">
        <%= render "form", post: @post %>

      </div>


    </div>
  </div>
</div>
<%#= link_to "New post", params[:topic_id].present? ? new_topic_post_path(@topic) : new_post_path %>
<div class="l">
  <p>
    <%= link_to "New post", params[:topic_id].present? ? new_topic_post_path(@topic) : new_post_path,class:"newbtn",data: {bs_toggle: 'modal',bs_target: '#exampleModal',remote: true} %>


  </p>
  <p>
    <%= will_paginate @posts %>
  </p>

</div>
<script>

    const f = document.querySelector('form');
    const loader=document.querySelector('.loader');
    const newbtn=document.querySelector('.newbtn');
    newbtn.addEventListener('click',function (){
        loader.classList.toggle('hide');

    });


    async function handleSubmit(event) {
        event.preventDefault();

        console.log(event.target.action);
        console.log(f.method);
        let data = new FormData(event.target);
        fetch(event.target.action, {
            method: f.method,
            body: data,
            headers: {
                'Accept': 'application/json'
            }
        }).then(response => {
            console.log(response);
            if (response.ok) {
                console.log("Form Submitted");
                document.querySelector('#exampleModal');
                alert('Post Created successfully');
                $('#exampleModal').modal('hide');
                loader.classList.toggle('hide');
                return response.json();

                // f.reset()
            } else {
                response.json().then(data => {
                    console.log(data.title[0])
                    console.log(data)
                    if (data.title[0]=="20 characters is the maximum allowed") {
                        alert("20 characters is the maximum allowed");
                        $('#exampleModal').modal('hide');
                        loader.classList.toggle('hide');
                    } else {
                        console.log("Oops! There was a problem submitting your form")
                    }
                })
            }
        }).then(data => {
            console.log(data)
        // }).catch
        // }(error=>{
        //     console.log(error)
        });
    }
    f.addEventListener("submit", handleSubmit)
</script>

app/views/posts/new.html.erb
<h1 class="text-center mt-4">New post</h1>



<br>

<div class="container col-5 mt-3">
  <%= render "form", post: @post %>
  <%= link_to "Back to posts", @topic %>
</div>

app/views/posts/new.js.erb
console.log("Hi");
$('#newUserForm').html(<%= escape_javascript render {'form',post: @post} %>);

app/views/posts/show.html.erb
<script>


  $(document).ready(function(){
      el=document.querySelector(".read");

      el1=document.querySelector(".read1");
      $.ajax({
          url: el.classList[1]+'/posts_users_read_statuses',
          type: "post",
          data:"",
          dataType: 'json',
          dataType: 'script',
          success:function (response){
              console.log("Success")
              el1.innerHTML=response
              return
          },
          error:function(response){
              console.log("Failed")
              el1.innerHTML=response
              return
          }

      })
  })
</script>

<p style="color: green"><%= notice %></p>
<div class="container">
<div class="position-relative ">
  <div class="position-relative top-0 start-0">
    <% if params[:topic_id].present? %>
      <h5 class="card-title"><%= @post.title %>(<%=@post.topic.field %>)</h5>
    <%end %>
    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>
  </div>
  <div class="read <%=@post.id %>">
    <p class="read1">Unseen</p>
  </div>
 <%#if @read %>
<!--    <p>Read</p>-->
  <%#else %>
<!--    <p>Unread</p>-->
    <%# @post.users << current_user %>
  <%#end %>
  <div class="position-absolute top-0 end-0">
    <p>
      <strong>Created By:</strong>
      <%= @post.user.email if @post.user %>
    </p>
  </div>

</div>
<!--<div class="col">-->
  <%#= render @post %>

<!--</div>-->

<div class="row mt-4">
  <div class="col">
    <% if @post.cover_picture.attached? %>
      <%= image_tag @post.cover_picture,class:"card-img-top"  %>
    <%end %>

  </div>




  <div class="col">
    <div class="row">
    <div class="col-6 ms-4">
      <strong>Comments:</strong>
      </br>
      <% @post.comments.each do |comment| %>
        <p>
          <%= comment.body %> | By: <%= comment.user.email if comment.user %>

        </p>
      <%end %>
      <%= link_to "User Ratings",post_comments_path(@post,@comment) %>
      <%= link_to "Add Comments",new_post_comment_path(@post,@comment) %>
    </div>
    <div class="col-2 ms-3">
      <strong>Tags:</strong>
      <% @post.tags.each do |tag| %>
        <%= link_to tag do %>
          <p><%= tag.name %><p>
        <%end %>
      <%end %>
    </div>
      <div class="col-3">


        <% @post.ratings.group(:star).count.each do |value,count| %>

          <% for i in (1..value) do %>
            <span class="fa fa-star " style="color:orange"></span>
          <%end %>
          <% for i in (1..(5-value)) do %>
            <span class="fa fa-star "></span>
          <%end %>
          <%= count %>
          <br />

        <% end %>



        <%= link_to "Add ratings",new_post_rating_path(@post) %>
      </div>
    </div>
      <!--<strong>Ratings</strong>-->
      <!--<br />-->

  </div>


  <div class="mt-4">
    <p>
<!--      <strong>Body:</strong>-->
      <%= @post.body %>
    </p>
  </div>

</div>
  <div class="position-relative mb-4">
  <div class="position-relative bottom-0 start-0" >
    <%= link_to "Edit this post", params[:topic_id].present? ? edit_topic_post_path(@topic,@post) : edit_post_path(@post) %> | <%= link_to "Back to posts", params[:topic_id].present? ? topic_posts_path(@topic) : posts_path %>
  </div>
  <div class="position-absolute bottom-0 start-50" >

    <%= button_to "Destroy this post", params[:topic_id].present? ? topic_post_path(@topic,@post): post_path(@post), method: :delete %>
  </div>
  </div>
</div>
</div>